#Bibliotecas

In [ ]:
from PIL import Image
import numpy as np

#Leer imagen

In [ ]:
def readImgPGM(path):
  # Open the PGM file
  img = Image.open(path)
  # Convert the image to a NumPy array
  img_array = np.array(img)

  # Display image information
  print(f"Image format: {img.format}")
  print(f"Image mode: {img.mode}") # L for grayscale
  print(f"Image size (width, height): {img.size}")

  return img_array


#Imprimir Imagen

In [ ]:
def printImg(img_array):
  # Convert the NumPy array back to a PIL Image object
  modified_img = Image.fromarray(img_array.astype('uint8'), 'L')

  # Save the modified image
  output_filename = "modified_output.pgm"
  modified_img.save(output_filename)
  print(f"\nModified image saved as {output_filename}")


#Prueba

In [ ]:

path = "eo.pgm"
arr = readImgPGM(path)
filas = 1200
columnas = 1200


Image format: PPM
Image mode: L
Image size (width, height): (1200, 1200)
[[44 44 44 ... 44 45 45]
 [42 41 41 ... 44 45 46]
 [44 43 42 ... 44 45 46]
 ...
 [37 35 33 ... 35 42 47]
 [37 36 34 ... 37 42 46]
 [37 36 35 ... 37 42 45]]

Modified image saved as modified_output.pgm


/tmp/ipython-input-2574278217.py:3: DeprecationWarning: 'mode' parameter is deprecated and will be removed in Pillow 13 (2026-10-15)
  modified_img = Image.fromarray(img_array.astype('uint8'), 'L')
